### ISSUE TITLE
extract and merge timewindows

### ISSUE THREAD

**Issue by ejwillemse** [ejwillemse/app_vukwm_bag_delivery#29]
business time are extracted using:

https://github.com/WasteLabs/dev_veolia_uk_westminster_bags_routing_engine/blob/master/notebooks/research/08_ejwillemse_20230113_extract_company_info_s3.ipynb

```yaml
opening_time_results:
  type: PartitionedDataSet
  path: s3://veolia-uk-platfrom/test/02_intermediate/opening_times/
  dataset:
    type: pandas.CSVDataSet
  filename_suffix: '.csv'
  credentials: dev_s3
```

the following code creates the short business description merge column:

```python
def extract_short_name_key(df):
   df =  df.assign(
        customer_short_name=df["Site Name"]
        .apply(lambda x: x.replace(".", ""))
        .apply(lambda x: x[: x.rfind("[")] if "[" in x else x)
        .apply(lambda x: x[: x.rfind("(")] if "(" in x else x)
        .str.strip()
        .str.lower()
        .replace("caffe concert", "caffe concerto")
        .replace("leon's carnaby", "leon's")
        .replace("leon's waterloo bridge - veolia es uk ltd", "leon's"),
    )
    return df
```

the following logic is applied when figuring out delivery hours:

1. Businesses can receive bags one hour before the listed opening times. 
2. For night-time business, we assume they can receive orders from 16h onwards. 
3. For those without opening times, we will assume they can take deliveries between 10 AM and 16 PM.
